name: dart_dfu
description: Modern nRF DFU package
version: 0.0.4
homepage: https://github.com/vincent290587/dart_dfu

environment:
  sdk: ^3.2.0

dependencies:

  retry: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
